public class ConsecutiveRevenueDays {

    /*
    * As a growing startup, we are trying to optimize our revenue and increase profitability. We have historical data
    * on our sales performance in the form of an integer array, where each element represents the revenue generated
    * on a particular day. Note that on some days, our company lost money as the revenue was negative.
    * We need a function that can help us find the subarray, or consecutive days, that generated the maximum revenue
    * in a given time period.Additionally, we need the function to return the total revenue generated by this subarray.
    *
    * Example 1:
    *   revenue = {1, -2, 3, 4, -5, 6, 7, -8, 9}
    *   startDay = 1
    *   endDay = 8
    *   Output: [2, 8, 15]
    * Explanation:
    *   The subarray with the maximum revenue is {3, 4, -5, 6, 7}, which generates a total revenue of 15.
    *   The function should return an array with three elements: the starting index of the subarray (2),
    *   the ending index of the subarray (8), and the total revenue generated by the subarray (15).
    *
    * Example 2:
    *   revenue = {-1, -2, -3, -4, -5}
    *   startDay = 0
    *   endDay = 4
    *   Output: [0, 0, -1]
    * Explanation:
    *   The subarray with the maximum revenue is { -1}, which generates a total revenue of -1. which generates a
    *   total revenue of -1. The function should return an array with three elements: the starting index
    *   of the subarray (0), the ending index of the subarray (0), and the total revenue generated by the subarray (-1).
     *
     * */
}
